### ISSUE TITLE
Compile error when running lein repl

### ISSUE THREAD

**Issue by danielcompton** [capitalone/cqrs-manager-for-distributed-reactive-services#14]
From a fresh checkout on master I get a compile error:

<details>

```sh
$ lein repl
...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: com.capitalone.commander.grpc.CommanderProtos, compiling:(com/capitalone/commander/grpc.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7441)
        at clojure.lang.RT.loadResourceScript(RT.java:374)
        at clojure.lang.RT.loadResourceScript(RT.java:365)
        at clojure.lang.RT.load(RT.java:455)
        at clojure.lang.RT.load(RT.java:421)
        at clojure.core$load$fn__7821.invoke(core.clj:6008)
        at clojure.core$load.invokeStatic(core.clj:6007)
        at clojure.core$load.doInvoke(core.clj:5991)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5812)
        at clojure.core$load_one.invoke(core.clj:5807)
        at clojure.core$load_lib$fn__7766.invoke(core.clj:5852)
        at clojure.core$load_lib.invokeStatic(core.clj:5851)
        at clojure.core$load_lib.doInvoke(core.clj:5832)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5889)
        at clojure.core$load_libs.doInvoke(core.clj:5873)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5911)
        at clojure.core$require.doInvoke(core.clj:5911)
        at clojure.lang.RestFn.invoke(RestFn.java:805)
        at com.capitalone.commander.rest.system$eval3654$loading__7707__auto____3655.invoke(system.clj:14)
        at com.capitalone.commander.rest.system$eval3654.invokeStatic(system.clj:14)
        at com.capitalone.commander.rest.system$eval3654.invoke(system.clj:14)
        at clojure.lang.Compiler.eval(Compiler.java:6977)
        at clojure.lang.Compiler.eval(Compiler.java:6966)
        at clojure.lang.Compiler.load(Compiler.java:7429)
        at clojure.lang.RT.loadResourceScript(RT.java:374)
        at clojure.lang.RT.loadResourceScript(RT.java:365)
        at clojure.lang.RT.load(RT.java:455)
        at clojure.lang.RT.load(RT.java:421)
        at clojure.core$load$fn__7821.invoke(core.clj:6008)
        at clojure.core$load.invokeStatic(core.clj:6007)
        at clojure.core$load.doInvoke(core.clj:5991)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5812)
        at clojure.core$load_one.invoke(core.clj:5807)
        at clojure.core$load_lib$fn__7766.invoke(core.clj:5852)
        at clojure.core$load_lib.invokeStatic(core.clj:5851)
        at clojure.core$load_lib.doInvoke(core.clj:5832)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$load_libs.invokeStatic(core.clj:5889)
        at clojure.core$load_libs.doInvoke(core.clj:5873)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:659)
        at clojure.core$require.invokeStatic(core.clj:5911)
        at clojure.core$require.doInvoke(core.clj:5911)
        at clojure.lang.RestFn.invoke(RestFn.java:2422)
        at user$eval13$loading__7707__auto____14.invoke(user.clj:14)
        at user$eval13.invokeStatic(user.clj:14)
        at user$eval13.invoke(user.clj:14)
        at clojure.lang.Compiler.eval(Compiler.java:6977)
        at clojure.lang.Compiler.eval(Compiler.java:6966)
        at clojure.lang.Compiler.load(Compiler.java:7429)
        at clojure.lang.RT.loadResourceScript(RT.java:374)
        at clojure.lang.RT.loadResourceScript(RT.java:361)
        at clojure.lang.RT.maybeLoadResourceScript(RT.java:357)
        at clojure.lang.RT.doInit(RT.java:479)
        at clojure.lang.RT.<clinit>(RT.java:333)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: com.capitalone.commander.grpc.CommanderProtos
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at clojure.lang.RT.classForName(RT.java:2183)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2196)
        at com.capitalone.commander.grpc$eval29370$loading__7707__auto____29371.invoke(grpc.clj:13)
        at com.capitalone.commander.grpc$eval29370.invokeStatic(grpc.clj:13)
        at com.capitalone.commander.grpc$eval29370.invoke(grpc.clj:13)
        at clojure.lang.Compiler.eval(Compiler.java:6977)
        at clojure.lang.Compiler.eval(Compiler.java:6966)
        at clojure.lang.Compiler.load(Compiler.java:7429)
        ... 62 more
```
</details>

It looks like the Java classes aren't being compiled. The project.clj looks like it should be doing this correctly though. Do you have any thoughts on how to fix this?

**Comment by danielcompton** [comment]
`:prep-tasks` don't seem to be run when calling `lein repl`. You can run `lein uberjar`, or `lein do javac, compile` to create them.

**Comment by bobby** [comment]
Hmm, maybe I'll add something to README about this.  Thanks for the report!
