### ISSUE TITLE
Getting error message when trying to start the app

### ISSUE THREAD

**Issue by inadarei** [capitalone/cqrs-manager-for-distributed-reactive-services#18]
When launching CMDR with an example service, per https://github.com/capitalone/cqrs-manager-for-distributed-reactive-services/pull/17 I am getting an error message:

```
kafka/kafka-clients/0.10.0.1/kafka-clients-0.10.0.1.jar:/root/.m2/repository/io/grpc/grpc-core/1.0.0/grpc-core-1.0.0.jar clojure.main -m
cmdr_1       | Exception in thread "main" java.lang.NullPointerException
cmdr_1       | 	at clojure.lang.Symbol.intern(Symbol.java:59)
cmdr_1       | 	at clojure.core$symbol.invokeStatic(core.clj:579)
cmdr_1       | 	at clojure.main$main_opt.invokeStatic(main.clj:316)
cmdr_1       | 	at clojure.main$main_opt.invoke(main.clj:312)
cmdr_1       | 	at clojure.main$main.invokeStatic(main.clj:423)
cmdr_1       | 	at clojure.main$main.doInvoke(main.clj:386)
cmdr_1       | 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
cmdr_1       | 	at clojure.lang.Var.applyTo(Var.java:700)
cmdr_1       | 	at clojure.main.main(main.java:37)
```

**Comment by bobby** [comment]
Hmm, let me dig into this one and get back to you.
